/*----- PROTECTED REGION ID(TemperatureMeter.h) ENABLED START -----*/
//=============================================================================
//
// file :        TemperatureMeter.h
//
// description : Include file for the TemperatureMeter class
//
// project :     Temperature Meter
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU Lesser General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Lesser General Public License for more details.
// 
// You should have received a copy of the GNU Lesser General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#ifndef TemperatureMeter_H
#define TemperatureMeter_H

#include <tango.h>
#include <time.h>
#include <cmath>


/*----- PROTECTED REGION END -----*/	//	TemperatureMeter.h

/**
 *  TemperatureMeter class description:
 *    
 */

namespace TemperatureMeter_ns
{
/*----- PROTECTED REGION ID(TemperatureMeter::Additional Class Declarations) ENABLED START -----*/

//	Additional Class Declarations

/*----- PROTECTED REGION END -----*/	//	TemperatureMeter::Additional Class Declarations

class TemperatureMeter : public TANGO_BASE_CLASS
{

/*----- PROTECTED REGION ID(TemperatureMeter::Data Members) ENABLED START -----*/

//	Add your own data members

/*----- PROTECTED REGION END -----*/	//	TemperatureMeter::Data Members


//	Attribute data members
public:
	Tango::DevDouble	*attr_temperature_read;

//	Constructors and destructors
public:
	/**
	 * Constructs a newly device object.
	 *
	 *	@param cl	Class.
	 *	@param s 	Device Name
	 */
	TemperatureMeter(Tango::DeviceClass *cl,string &s);
	/**
	 * Constructs a newly device object.
	 *
	 *	@param cl	Class.
	 *	@param s 	Device Name
	 */
	TemperatureMeter(Tango::DeviceClass *cl,const char *s);
	/**
	 * Constructs a newly device object.
	 *
	 *	@param cl	Class.
	 *	@param s 	Device name
	 *	@param d	Device description.
	 */
	TemperatureMeter(Tango::DeviceClass *cl,const char *s,const char *d);
	/**
	 * The device object destructor.
	 */	
	~TemperatureMeter() {delete_device();};


//	Miscellaneous methods
public:
	/*
	 *	will be called at device destruction or at init command.
	 */
	void delete_device();
	/*
	 *	Initialize the device
	 */
	virtual void init_device();
	/*
	 *	Always executed method before execution command method.
	 */
	virtual void always_executed_hook();


//	Attribute methods
public:
	//--------------------------------------------------------
	/*
	 *	Method      : TemperatureMeter::read_attr_hardware()
	 *	Description : Hardware acquisition for attributes.
	 */
	//--------------------------------------------------------
	virtual void read_attr_hardware(vector<long> &attr_list);

/**
 *	Attribute temperature related methods
 *	Description: 
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
	virtual void read_temperature(Tango::Attribute &attr);
	virtual bool is_temperature_allowed(Tango::AttReqType type);


	//--------------------------------------------------------
	/**
	 *	Method      : TemperatureMeter::add_dynamic_attributes()
	 *	Description : Add dynamic attributes if any.
	 */
	//--------------------------------------------------------
	void add_dynamic_attributes();



//	Command related methods
public:
	/**
	 *	Command Start related method
	 *	Description: 
	 *
	 *	@returns 
	 */
	virtual Tango::DevBoolean start();
	virtual bool is_Start_allowed(const CORBA::Any &any);
	/**
	 *	Command Stop related method
	 *	Description: 
	 *
	 *	@returns 
	 */
	virtual Tango::DevBoolean stop();
	virtual bool is_Stop_allowed(const CORBA::Any &any);


/*----- PROTECTED REGION ID(TemperatureMeter::Additional Method prototypes) ENABLED START -----*/

//	Additional Method prototypes

/*----- PROTECTED REGION END -----*/	//	TemperatureMeter::Additional Method prototypes
};

/*----- PROTECTED REGION ID(TemperatureMeter::Additional Classes Definitions) ENABLED START -----*/

//	Additional Classes Definitions

/*----- PROTECTED REGION END -----*/	//	TemperatureMeter::Additional Classes Definitions

}	//	End of namespace

#endif   //	TemperatureMeter_H
