/*----- PROTECTED REGION ID(TemperatureMeter.cpp) ENABLED START -----*/
static const char *RcsId = "$Id:  $";
//=============================================================================
//
// file :        TemperatureMeter.cpp
//
// description : C++ source for the TemperatureMeter class and its commands.
//               The class is derived from Device. It represents the
//               CORBA servant object which will be accessed from the
//               network. All commands which can be executed on the
//               TemperatureMeter are implemented in this file.
//
// project :     Temperature Meter
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU Lesser General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Lesser General Public License for more details.
// 
// You should have received a copy of the GNU Lesser General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#include <TemperatureMeter.h>
#include <TemperatureMeterClass.h>

/*----- PROTECTED REGION END -----*/	//	TemperatureMeter.cpp

/**
 *  TemperatureMeter class description:
 *    
 */

//================================================================
//  The following table gives the correspondence
//  between command and method names.
//
//  Command name  |  Method name
//================================================================
//  State         |  Inherited (no method)
//  Status        |  Inherited (no method)
//  Start         |  start
//  Stop          |  stop
//================================================================

//================================================================
//  Attributes managed is:
//================================================================
//  temperature  |  Tango::DevDouble	Scalar
//================================================================

namespace TemperatureMeter_ns
{
/*----- PROTECTED REGION ID(TemperatureMeter::namespace_starting) ENABLED START -----*/

//	static initializations

/*----- PROTECTED REGION END -----*/	//	TemperatureMeter::namespace_starting

//--------------------------------------------------------
/**
 *	Method      : TemperatureMeter::TemperatureMeter()
 *	Description : Constructors for a Tango device
 *                implementing the classTemperatureMeter
 */
//--------------------------------------------------------
TemperatureMeter::TemperatureMeter(Tango::DeviceClass *cl, string &s)
 : TANGO_BASE_CLASS(cl, s.c_str())
{
	/*----- PROTECTED REGION ID(TemperatureMeter::constructor_1) ENABLED START -----*/
	init_device();
	
	/*----- PROTECTED REGION END -----*/	//	TemperatureMeter::constructor_1
}
//--------------------------------------------------------
TemperatureMeter::TemperatureMeter(Tango::DeviceClass *cl, const char *s)
 : TANGO_BASE_CLASS(cl, s)
{
	/*----- PROTECTED REGION ID(TemperatureMeter::constructor_2) ENABLED START -----*/
	init_device();
	
	/*----- PROTECTED REGION END -----*/	//	TemperatureMeter::constructor_2
}
//--------------------------------------------------------
TemperatureMeter::TemperatureMeter(Tango::DeviceClass *cl, const char *s, const char *d)
 : TANGO_BASE_CLASS(cl, s, d)
{
	/*----- PROTECTED REGION ID(TemperatureMeter::constructor_3) ENABLED START -----*/
	init_device();
	
	/*----- PROTECTED REGION END -----*/	//	TemperatureMeter::constructor_3
}

//--------------------------------------------------------
/**
 *	Method      : TemperatureMeter::delete_device()
 *	Description : will be called at device destruction or at init command
 */
//--------------------------------------------------------
void TemperatureMeter::delete_device()
{
	DEBUG_STREAM << "TemperatureMeter::delete_device() " << device_name << endl;
	/*----- PROTECTED REGION ID(TemperatureMeter::delete_device) ENABLED START -----*/
	
	//	Delete device allocated objects
	
	/*----- PROTECTED REGION END -----*/	//	TemperatureMeter::delete_device
	delete[] attr_temperature_read;
}

//--------------------------------------------------------
/**
 *	Method      : TemperatureMeter::init_device()
 *	Description : will be called at device initialization.
 */
//--------------------------------------------------------
void TemperatureMeter::init_device()
{
	DEBUG_STREAM << "TemperatureMeter::init_device() create device " << device_name << endl;
	/*----- PROTECTED REGION ID(TemperatureMeter::init_device_before) ENABLED START -----*/
	
	//	Initialization before get_device_property() call
	
	/*----- PROTECTED REGION END -----*/	//	TemperatureMeter::init_device_before
	
	//	No device property to be read from database
	
	attr_temperature_read = new Tango::DevDouble[1];

	/*----- PROTECTED REGION ID(TemperatureMeter::init_device) ENABLED START -----*/
	
	//	Initialize device
	
	/*----- PROTECTED REGION END -----*/	//	TemperatureMeter::init_device
}


//--------------------------------------------------------
/**
 *	Method      : TemperatureMeter::always_executed_hook()
 *	Description : method always executed before any command is executed
 */
//--------------------------------------------------------
void TemperatureMeter::always_executed_hook()
{
	INFO_STREAM << "TemperatureMeter::always_executed_hook()  " << device_name << endl;
	/*----- PROTECTED REGION ID(TemperatureMeter::always_executed_hook) ENABLED START -----*/
	
	//	code always executed before all requests
	
	/*----- PROTECTED REGION END -----*/	//	TemperatureMeter::always_executed_hook
}

//--------------------------------------------------------
/**
 *	Method      : TemperatureMeter::read_attr_hardware()
 *	Description : Hardware acquisition for attributes
 */
//--------------------------------------------------------
void TemperatureMeter::read_attr_hardware(TANGO_UNUSED(vector<long> &attr_list))
{
	DEBUG_STREAM << "TemperatureMeter::read_attr_hardware(vector<long> &attr_list) entering... " << endl;
	/*----- PROTECTED REGION ID(TemperatureMeter::read_attr_hardware) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	TemperatureMeter::read_attr_hardware
}

//--------------------------------------------------------
/**
 *	Read attribute temperature related method
 *	Description: 
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void TemperatureMeter::read_temperature(Tango::Attribute &attr)
{
	DEBUG_STREAM << "TemperatureMeter::read_temperature(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(TemperatureMeter::read_temperature) ENABLED START -----*/
	//	Set the attribute value
	attr.set_value(attr_temperature_read);
	
	/*----- PROTECTED REGION END -----*/	//	TemperatureMeter::read_temperature
}

//--------------------------------------------------------
/**
 *	Method      : TemperatureMeter::add_dynamic_attributes()
 *	Description : Create the dynamic attributes if any
 *                for specified device.
 */
//--------------------------------------------------------
void TemperatureMeter::add_dynamic_attributes()
{
	/*----- PROTECTED REGION ID(TemperatureMeter::add_dynamic_attributes) ENABLED START -----*/
	
	//	Add your own code to create and add dynamic attributes if any
	
	/*----- PROTECTED REGION END -----*/	//	TemperatureMeter::add_dynamic_attributes
}

//--------------------------------------------------------
/**
 *	Command Start related method
 *	Description: 
 *
 *	@returns 
 */
//--------------------------------------------------------
Tango::DevBoolean TemperatureMeter::start()
{
	Tango::DevBoolean argout;
	DEBUG_STREAM << "TemperatureMeter::Start()  - " << device_name << endl;
	/*----- PROTECTED REGION ID(TemperatureMeter::start) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	TemperatureMeter::start
	return argout;
}
//--------------------------------------------------------
/**
 *	Command Stop related method
 *	Description: 
 *
 *	@returns 
 */
//--------------------------------------------------------
Tango::DevBoolean TemperatureMeter::stop()
{
	Tango::DevBoolean argout;
	DEBUG_STREAM << "TemperatureMeter::Stop()  - " << device_name << endl;
	/*----- PROTECTED REGION ID(TemperatureMeter::stop) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	TemperatureMeter::stop
	return argout;
}

/*----- PROTECTED REGION ID(TemperatureMeter::namespace_ending) ENABLED START -----*/

//	Additional Methods

/*----- PROTECTED REGION END -----*/	//	TemperatureMeter::namespace_ending
} //	namespace
